services:
  db:
    image: ymorpheus/nodejs2024q1-service-db
    container_name: 
      db
    build:
      dockerfile: ./docker/db.Dockerfile
    networks:
      - internal
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    image: ymorpheus/nodejs2024q1-service-app:v.2.1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
    networks:
      - internal
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=$PORT
      - DATABASE_URL=$DATABASE_URL
      - LOG_LEVEL=$LOG_LEVEL
      - LOG_FILE_SIZE=$LOG_FILE_SIZE
      - LOGS_FOLDER_PATH=$LOGS_FOLDER_PATH
    ports:
      - $PORT:$PORT
    volumes:
      - /usr/src/app/node_modules
      - ./src:/usr/src/app/src

volumes:
  pg_data:

networks:
  internal:
    driver: bridge
    name: 'internal'